[package]
name = "chatopus"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "chatopus_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [] }
tauri-plugin-shell = "2.0.0-rc"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "^0.12", features = ["json"] }
parking_lot = "*"
futures-util = "0.3.30"
runtimelib = {  path = "../runtimed/runtimelib" }
runtimed = {  path = "../runtimed/runtimed" }
tokio = "1.39.2"
anyhow = "1.0.86"
tabled = "0.15.0"

